// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypmoaoagvmarvrsztexp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwbW9hb2Fndm1hcnZyc3p0ZXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzQ0ODEsImV4cCI6MjA2ODQ1MDQ4MX0.aDBFcK0KBs4acY7td3UgfWANhBjvuoVc03iX42lZiW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});